//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroyLeeMVCEF.BookingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookingService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Pass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doctors", ReplyAction="*")]
        TroyLeeMVCEF.BookingService.DoctorsResponse Doctors(TroyLeeMVCEF.BookingService.DoctorsRequest request);
        
        // CODEGEN: Generating message contract since element name StrJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Booking", ReplyAction="*")]
        TroyLeeMVCEF.BookingService.BookingResponse Booking(TroyLeeMVCEF.BookingService.BookingRequest request);
        
        // CODEGEN: Generating message contract since element name doctorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AvailableDatesByDoctor", ReplyAction="*")]
        TroyLeeMVCEF.BookingService.AvailableDatesByDoctorResponse AvailableDatesByDoctor(TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequest request);
        
        // CODEGEN: Generating message contract since element name doctorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AvailableHoursByDoctor", ReplyAction="*")]
        TroyLeeMVCEF.BookingService.AvailableHoursByDoctorResponse AvailableHoursByDoctor(TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoctorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doctors", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.DoctorsRequestBody Body;
        
        public DoctorsRequest() {
        }
        
        public DoctorsRequest(TroyLeeMVCEF.BookingService.DoctorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoctorsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int numofrecords;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pass;
        
        public DoctorsRequestBody() {
        }
        
        public DoctorsRequestBody(int index, int numofrecords, string Pass) {
            this.index = index;
            this.numofrecords = numofrecords;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoctorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoctorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.DoctorsResponseBody Body;
        
        public DoctorsResponse() {
        }
        
        public DoctorsResponse(TroyLeeMVCEF.BookingService.DoctorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoctorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoctorsResult;
        
        public DoctorsResponseBody() {
        }
        
        public DoctorsResponseBody(string DoctorsResult) {
            this.DoctorsResult = DoctorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Booking", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.BookingRequestBody Body;
        
        public BookingRequest() {
        }
        
        public BookingRequest(TroyLeeMVCEF.BookingService.BookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public BookingRequestBody() {
        }
        
        public BookingRequestBody(string StrJson, string Pass) {
            this.StrJson = StrJson;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.BookingResponseBody Body;
        
        public BookingResponse() {
        }
        
        public BookingResponse(TroyLeeMVCEF.BookingService.BookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookingResult;
        
        public BookingResponseBody() {
        }
        
        public BookingResponseBody(string BookingResult) {
            this.BookingResult = BookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvailableDatesByDoctorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvailableDatesByDoctor", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequestBody Body;
        
        public AvailableDatesByDoctorRequest() {
        }
        
        public AvailableDatesByDoctorRequest(TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableDatesByDoctorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Pass;
        
        public AvailableDatesByDoctorRequestBody() {
        }
        
        public AvailableDatesByDoctorRequestBody(string doctorId, int month, int year, string Pass) {
            this.doctorId = doctorId;
            this.month = month;
            this.year = year;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvailableDatesByDoctorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvailableDatesByDoctorResponse", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.AvailableDatesByDoctorResponseBody Body;
        
        public AvailableDatesByDoctorResponse() {
        }
        
        public AvailableDatesByDoctorResponse(TroyLeeMVCEF.BookingService.AvailableDatesByDoctorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableDatesByDoctorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AvailableDatesByDoctorResult;
        
        public AvailableDatesByDoctorResponseBody() {
        }
        
        public AvailableDatesByDoctorResponseBody(string AvailableDatesByDoctorResult) {
            this.AvailableDatesByDoctorResult = AvailableDatesByDoctorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvailableHoursByDoctorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvailableHoursByDoctor", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequestBody Body;
        
        public AvailableHoursByDoctorRequest() {
        }
        
        public AvailableHoursByDoctorRequest(TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableHoursByDoctorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime datetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pass;
        
        public AvailableHoursByDoctorRequestBody() {
        }
        
        public AvailableHoursByDoctorRequestBody(string doctorId, System.DateTime datetime, string Pass) {
            this.doctorId = doctorId;
            this.datetime = datetime;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvailableHoursByDoctorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvailableHoursByDoctorResponse", Namespace="http://tempuri.org/", Order=0)]
        public TroyLeeMVCEF.BookingService.AvailableHoursByDoctorResponseBody Body;
        
        public AvailableHoursByDoctorResponse() {
        }
        
        public AvailableHoursByDoctorResponse(TroyLeeMVCEF.BookingService.AvailableHoursByDoctorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableHoursByDoctorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AvailableHoursByDoctorResult;
        
        public AvailableHoursByDoctorResponseBody() {
        }
        
        public AvailableHoursByDoctorResponseBody(string AvailableHoursByDoctorResult) {
            this.AvailableHoursByDoctorResult = AvailableHoursByDoctorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : TroyLeeMVCEF.BookingService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TroyLeeMVCEF.BookingService.Service1Soap>, TroyLeeMVCEF.BookingService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TroyLeeMVCEF.BookingService.DoctorsResponse TroyLeeMVCEF.BookingService.Service1Soap.Doctors(TroyLeeMVCEF.BookingService.DoctorsRequest request) {
            return base.Channel.Doctors(request);
        }
        
        public string Doctors(int index, int numofrecords, string Pass) {
            TroyLeeMVCEF.BookingService.DoctorsRequest inValue = new TroyLeeMVCEF.BookingService.DoctorsRequest();
            inValue.Body = new TroyLeeMVCEF.BookingService.DoctorsRequestBody();
            inValue.Body.index = index;
            inValue.Body.numofrecords = numofrecords;
            inValue.Body.Pass = Pass;
            TroyLeeMVCEF.BookingService.DoctorsResponse retVal = ((TroyLeeMVCEF.BookingService.Service1Soap)(this)).Doctors(inValue);
            return retVal.Body.DoctorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TroyLeeMVCEF.BookingService.BookingResponse TroyLeeMVCEF.BookingService.Service1Soap.Booking(TroyLeeMVCEF.BookingService.BookingRequest request) {
            return base.Channel.Booking(request);
        }
        
        public string Booking(string StrJson, string Pass) {
            TroyLeeMVCEF.BookingService.BookingRequest inValue = new TroyLeeMVCEF.BookingService.BookingRequest();
            inValue.Body = new TroyLeeMVCEF.BookingService.BookingRequestBody();
            inValue.Body.StrJson = StrJson;
            inValue.Body.Pass = Pass;
            TroyLeeMVCEF.BookingService.BookingResponse retVal = ((TroyLeeMVCEF.BookingService.Service1Soap)(this)).Booking(inValue);
            return retVal.Body.BookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TroyLeeMVCEF.BookingService.AvailableDatesByDoctorResponse TroyLeeMVCEF.BookingService.Service1Soap.AvailableDatesByDoctor(TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequest request) {
            return base.Channel.AvailableDatesByDoctor(request);
        }
        
        public string AvailableDatesByDoctor(string doctorId, int month, int year, string Pass) {
            TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequest inValue = new TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequest();
            inValue.Body = new TroyLeeMVCEF.BookingService.AvailableDatesByDoctorRequestBody();
            inValue.Body.doctorId = doctorId;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.Pass = Pass;
            TroyLeeMVCEF.BookingService.AvailableDatesByDoctorResponse retVal = ((TroyLeeMVCEF.BookingService.Service1Soap)(this)).AvailableDatesByDoctor(inValue);
            return retVal.Body.AvailableDatesByDoctorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TroyLeeMVCEF.BookingService.AvailableHoursByDoctorResponse TroyLeeMVCEF.BookingService.Service1Soap.AvailableHoursByDoctor(TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequest request) {
            return base.Channel.AvailableHoursByDoctor(request);
        }
        
        public string AvailableHoursByDoctor(string doctorId, System.DateTime datetime, string Pass) {
            TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequest inValue = new TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequest();
            inValue.Body = new TroyLeeMVCEF.BookingService.AvailableHoursByDoctorRequestBody();
            inValue.Body.doctorId = doctorId;
            inValue.Body.datetime = datetime;
            inValue.Body.Pass = Pass;
            TroyLeeMVCEF.BookingService.AvailableHoursByDoctorResponse retVal = ((TroyLeeMVCEF.BookingService.Service1Soap)(this)).AvailableHoursByDoctor(inValue);
            return retVal.Body.AvailableHoursByDoctorResult;
        }
    }
}
